{
 "title": "PowerDNS metrics",
 "description": "Shows all available metrics of the PowerDNS authoritative name server.",
 "tags": [
  "dns",
  "powerdns"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "query": "pdns.*" },
   {
    "name": "interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "DB problems",
   "type": "stat",
   "description": "Packets that could not be answered due to database problems",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.servfail-packets)), 'DB problems')"
    }
   ]
  },
  {
   "title": "DB queue",
   "type": "stat",
   "description": "Packets waiting for database attention",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.qsize-q)), 'DB queue')"
    }
   ]
  },
  {
   "title": "Queries/s vs. Answers/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.{udp,tcp}-queries)), 'queries')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.{udp,tcp}-answers)), 'answers')"
    }
   ]
  },
  {
   "title": "Overload drops",
   "type": "stat",
   "description": "Questions dropped because backends overloaded",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.overload-drops)), 'Overload drops')"
    }
   ]
  },
  {
   "title": "UDP in errors",
   "type": "stat",
   "description": "Packets received faster than the OS could process them",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.udp-in-errors)), 'UDP in errors')"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(perSecond(aliasByNode(pdns.$host.auth.latency, 1)), 0)"
    }
   ]
  },
  {
   "title": "Incoming Notifications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.incoming-notifications)), 'notifications')"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(summarize(groupByNode(pdns.$host.auth.{udp4,tcp4}-queries, 3, 'sum'), '$interval', 'sum', false), 0), '(udp|tcp)\\d-queries', '\\1 v4')"
    },
    {
     "target": "aliasSub(aliasByNode(summarize(groupByNode(pdns.$host.auth.{udp6,tcp6}-queries, 3, 'sum'), '$interval', 'sum', false), 0), '(udp|tcp)\\d-queries', '\\1 v6')"
    }
   ]
  },
  {
   "title": "Recursion Queries/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.recursing-answers)), 'answers')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.recursing-questions)), 'questions')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.recursion-unanswered)), 'unanswered')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.rd-queries)), 'requested')"
    }
   ]
  },
  {
   "title": "Packet Cache Hits/s vs. Misses/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.packetcache-hit)), 'hits')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.packetcache-miss)), 'misses')"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(sumSeries(pdns.$host.auth.key-cache-size), 'key-cache')"
    },
    {
     "target": "alias(sumSeries(pdns.$host.auth.meta-cache-size), 'meta-cache')"
    },
    {
     "target": "alias(sumSeries(pdns.$host.auth.packetcache-size), 'packet-cache')"
    },
    {
     "target": "alias(sumSeries(pdns.$host.auth.query-cache-size), 'query-cache')"
    },
    {
     "target": "alias(sumSeries(pdns.$host.auth.signature-cache-size), 'signature-cache')"
    }
   ]
  },
  {
   "title": "Query Cache Hits/s vs. Misses/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.query-cache-hit)), 'hits')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.query-cache-miss)), 'misses')"
    }
   ]
  },
  {
   "title": "DNS updates received vs. answered",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.dnsupdate-answers)), 'answered')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.dnsupdate-queries)), 'received')"
    }
   ]
  },
  {
   "title": "DNS update changes vs. refused",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.dnsupdate-changes)), 'changes')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.auth.dnsupdate-refused)), 'refused')"
    }
   ]
  }
 ]
}