{
 "title": "PowerDNS recursor metrics",
 "description": "Shows all available metrics of the PowerDNS recursor resolving name server.",
 "tags": [
  "powerdns",
  "recursor"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "host", "query": "pdns.*" }
  ]
 },
 "panels": [
  {
   "title": "Unreachables",
   "type": "stat",
   "description": "Unreachable nameservers",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "perSecond(sumSeries(pdns.$host.recursor.unreachables))"
    }
   ]
  },
  {
   "title": "Unauthorized",
   "type": "stat",
   "description": "Denied questions because of allow-from restrictions",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "perSecond(sumSeries(pdns.$host.recursor.unauthorized-*))"
    }
   ]
  },
  {
   "title": "QpS",
   "type": "stat",
   "description": "Queries per Second",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.recursor.questions)), 'questions')"
    }
   ]
  },
  {
   "title": "Questions/s vs. Answers/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.recursor.questions)), 'questions')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.recursor.nxdomain-answers)), 'nxdomain-answers')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.recursor.servfail-answers)), 'servfail-answers')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.recursor.noerror-answers)), 'noerror-answers')"
    }
   ]
  },
  {
   "title": "Query Pipe Full Drops",
   "type": "stat",
   "description": "Questions dropped because the query distribution pipe was full",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "perSecond(alias(sumSeries(pdns.$host.recursor.query-pipe-full-drops), 'query-pup-full-drops'))"
    }
   ]
  },
  {
   "title": "Resource Limits Drops",
   "type": "stat",
   "description": "Queries that could not be performed because of resource limits",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "perSecond(alias(sumSeries(pdns.$host.recursor.resource-limits), 'resource-limits'))"
    }
   ]
  },
  {
   "title": "Time To Answer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.recursor.answers0-1)), '1ms')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.recursor.answers1-10)), '10 ms')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.recursor.answers10-100)), '100ms')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.recursor.answers100-1000)), '1s')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.recursor.answers-slow)), '> 1s')"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(pdns.$host.recursor.qa-latency, 1)"
    }
   ]
  },
  {
   "title": "Packet Cache Hits/s vs. Misses/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.recursor.packetcache-hits)), 'hits')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.recursor.packetcache-misses)), 'misses')"
    }
   ]
  },
  {
   "title": "Packet Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(sumSeries(pdns.$host.recursor.max-packetcache-entries), 'max')"
    },
    {
     "target": "alias(sumSeries(pdns.$host.recursor.packetcache-entries), 'entries')"
    }
   ]
  },
  {
   "title": "Cache Hits/s vs. Misses/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.recursor.cache-hits)), 'hits')"
    },
    {
     "target": "alias(perSecond(sumSeries(pdns.$host.recursor.cache-misses)), 'misses')"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(sumSeries(pdns.$host.recursor.max-cache-entries), 'max')"
    },
    {
     "target": "alias(sumSeries(pdns.$host.recursor.cache-entries), 'entries')"
    },
    {
     "target": "alias(sumSeries(pdns.$host.recursor.negcache-entries), 'negcache')"
    }
   ]
  }
 ]
}